
image: danieldent/docker-builder

build:
  services:
    - docker:dind
  script:
    - docker version
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build ${DOCKER_BUILD_ARGS} --force-rm --no-cache --pull -t ci-${CI_BUILD_ID} .
    - gitlab-ci-docker-retag.sh ci-${CI_BUILD_ID} $CI_REGISTRY_IMAGE 1 1 master

deploy:
  stage: deploy
  environment:
    name: $CI_BUILD_REF_NAME
  variables:
    NGINX_ACTIVE_LB_DRAINPLUG_SUFFIX: "example.com"
    NGINX_ACTIVE_LB_CERTIFICATE_VOLUME: "letsencrypt-certs"
  only:
    - /^env-.*$/
    - blue
    - green
  tags:
    - deploy
  script:
    - SERVICE_COLOR=$CI_BUILD_REF_NAME rancher-compose -p rancher-nginx-active-lb-$CI_BUILD_REF_NAME up -d -u
