lb:
  image: $CI_REGISTRY_IMAGE:sha-$CI_BUILD_REF
  ports:
    - 80:80
    - 443:443
  volumes:
    - "$NGINX_ACTIVE_LB_CERTIFICATE_VOLUME:/data/certs"
  labels:
    io.rancher.scheduler.global: True
    io.rancher.scheduler.affinity:host_label: lb-$SERVICE_COLOR=True

drain-plug:
  image: nginx
  expose:
    - 80
  labels:
    io.rancher.scheduler.global: True
    io.rancher.scheduler.affinity:host_label: lb-$SERVICE_COLOR=True
    com.danieldent.rancher-nginx-active-lb.published-host: $SERVICE_COLOR.$NGINX_ACTIVE_LB_DRAINPLUG_SUFFIX
    com.danieldent.rancher-lets-encrypt.hosts: $SERVICE_COLOR.$NGINX_ACTIVE_LB_DRAINPLUG_SUFFIX
