#!/usr/bin/with-contenv bash

while ! ([ -f /etc/nginx/nginx.conf ] && nginx -t -c /etc/nginx/nginx.conf); do
    echo "Waiting for a valid nginx.conf to exist..."
    sleep 1s
done

exec nginx -g 'daemon off;'
